module Hackney
  module Tenancy
    module ActionCodes
      AUTOMATED_SMS_ACTION_CODE = 'GAT'.freeze
      AUTOMATED_EMAIL_ACTION_CODE = 'GAE'.freeze

      MANUAL_SMS_ACTION_CODE = 'GMS'.freeze
      MANUAL_EMAIL_ACTION_CODE = 'GME'.freeze

      MANUAL_GREEN_SMS_ACTION_CODE = 'GMS'.freeze
      MANUAL_AMBER_SMS_ACTION_CODE = 'AMS'.freeze

      LETTER_FAILED_VALIDATION_CODE = 'VFL'.freeze
      # Codes for letters as follows:
      LETTER_1_IN_ARREARS_FH = 'LF1'.freeze
      LETTER_2_IN_ARREARS_FH = 'LF2'.freeze
      LETTER_1_IN_ARREARS_LH = 'LL1'.freeze
      LETTER_2_IN_ARREARS_LH = 'LL2'.freeze
      LETTER_1_IN_ARREARS_SO = 'LS1'.freeze
      LETTER_2_IN_ARREARS_SO = 'LS2'.freeze

      INCOME_COLLECTION_LETTER_1 = 'IC1'.freeze
      INCOME_COLLECTION_LETTER_1_UH = 'S01'.freeze

      INCOME_COLLECTION_LETTER_2 = 'IC2'.freeze
      INCOME_COLLECTION_LETTER_2_UH = 'S02'.freeze
      INCOME_COLLECTION_LETTER_2_UH_ALT = 'ZR2'.freeze
      INCOME_COLLECTION_LETTER_2_UH_ALT_2 = 'ZL2'.freeze
      INCOME_COLLECTION_LETTER_2_UH_ALT_3 = 'ZT2'.freeze

      PRE_NOSP_WARNING_LETTER_SENT = 'IC3'.freeze
      COURT_WARNING_LETTER_SENT = 'IC4'.freeze
      COURT_BREACH_LETTER_SENT = 'CBL'.freeze

      FIRST_FTA_LETTER_SENT = 'C'.freeze
      ARREARS_MAIL_MERGE_LETTER_SENT = 'MML'.freeze
      S0A_ALTERNATIVE_LETTER = 'S0A'.freeze
      FTA_REFUND_REQUEST_LETTER_SENT = 'REF'.freeze
      MW_LETTER_ACTION_1_COMPLETED = 'ZW1'.freeze
      MW_LETTER_ACTION_2_COMPLETED = 'ZW2'.freeze
      MW_LBA_LETTER_COMPLETED = 'ZW3'.freeze
      MW_LETTER_ACTION_1 = 'MW1'.freeze
      MW_LETTER_ACTION_2 = 'MW2'.freeze
      MW_LBA_LETTER = 'MW3'.freeze
      TEXT_MESSAGE_SENT = 'SMS'.freeze
      STAGE_ONE_COMPLETE = 'ZR1'.freeze
      STAGE_THREE_COMPLETE = 'ZR3'.freeze

      VISIT_MADE = 'VIM'.freeze

      ADJOURNED_ON_TERMS_COURT_OUTCOME = 'ADT'.freeze
      POSTPONED_POSSESSIOON_COURT_OUTCOME = 'PPO'.freeze
      SUSPENDED_POSSESSION_COURT_OUTCOME = 'SPO'.freeze

      FOR_UH_CRITERIA_SQL = [
        INCOME_COLLECTION_LETTER_1, INCOME_COLLECTION_LETTER_1_UH, INCOME_COLLECTION_LETTER_2,
        INCOME_COLLECTION_LETTER_2_UH_ALT, INCOME_COLLECTION_LETTER_2_UH_ALT_2,
        INCOME_COLLECTION_LETTER_2_UH_ALT_3, PRE_NOSP_WARNING_LETTER_SENT, COURT_WARNING_LETTER_SENT,
        LETTER_1_IN_ARREARS_FH, LETTER_2_IN_ARREARS_FH, LETTER_1_IN_ARREARS_LH,
        LETTER_2_IN_ARREARS_LH, LETTER_1_IN_ARREARS_SO, LETTER_2_IN_ARREARS_SO,
        AUTOMATED_SMS_ACTION_CODE, AUTOMATED_EMAIL_ACTION_CODE, MANUAL_SMS_ACTION_CODE,
        MANUAL_EMAIL_ACTION_CODE, MANUAL_AMBER_SMS_ACTION_CODE, FIRST_FTA_LETTER_SENT,
        ARREARS_MAIL_MERGE_LETTER_SENT, S0A_ALTERNATIVE_LETTER, FTA_REFUND_REQUEST_LETTER_SENT,
        MW_LETTER_ACTION_1_COMPLETED, MW_LETTER_ACTION_2_COMPLETED, MW_LBA_LETTER_COMPLETED,
        MW_LETTER_ACTION_1, MW_LETTER_ACTION_2, MW_LBA_LETTER, TEXT_MESSAGE_SENT,
        STAGE_ONE_COMPLETE, STAGE_THREE_COMPLETE, COURT_BREACH_LETTER_SENT, VISIT_MADE
      ].freeze
    end
  end
end
