version: '3.1'
services:
  app:
    build: .
    environment:
      - UH_DATABASE_NAME=uhsimulator
      - UH_DATABASE_USERNAME=sa
      - UH_DATABASE_PASSWORD=Rooty-Tooty
      - UH_DATABASE_HOST=universal_housing_simulator
      - UH_DATABASE_PORT=1433
      - REDIS_URL=redis://redis:6379
      - AWS_REGION=eu-west-2
      - CUSTOMER_MANAGED_KEY=${CUSTOMER_MANAGED_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - GOV_NOTIFY_API_KEY=${GOV_NOTIFY_API_KEY}
      - MYSQL_USERNAME=foo
      - MYSQL_PASSWORD=bar
      - MYSQL_ROOT_PASSWORD=bar
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: sh -c 'rails db:migrate && rails s --binding=0.0.0.0'
    depends_on:
      - universal_housing_simulator
      - redis
      - db
  universal_housing_simulator:
    image: 775052747630.dkr.ecr.eu-west-2.amazonaws.com/hackney/universal-housing-simulator-loaded:latest
    ports:
      - 1433:1433
  redis:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
  db:
    image: mysql:5.7
    volumes:
      - ${PWD}/db/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USERNAME=foo
      - MYSQL_PASSWORD=bar
      - MYSQL_ROOT_PASSWORD=bar
    ports:
      - "3307:3306"
    expose:
      - '3306'
  # db-test:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=app-database-test
  #     - MYSQL_USERNAME=foo
  #     - MYSQL_PASSWORD=bar
  #     - MYSQL_ROOT_PASSWORD=bar
  #   volumes:
  #     - test_data:/var/lib/mysql
  #   ports:
  #     - "3308:3309"
  #   expose:
  #     - '3309'
