# All environments are injected via DATABASE_URL

development:
  adapter: mysql2
  encoding: utf8
  database: app-database-<%= ENV.fetch("RAILS_ENV") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: db
test:
  adapter: mysql2
  encoding: utf8
  database: app-database-<%= ENV.fetch("RAILS_ENV") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: db

  # staging and production should be injected via DATABASE_URL
